# Site settings
# baseurl = "https://litrans.ca/"
baseurl = "/"
languageCode = "en-us"
title = "LiTrans"
theme = ""
publishDir = "public"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-137871044-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  # name = "Your name"
  # description = "Your description"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = ["css/plugins/animate-css/animate.css"]
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit "

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand       = "LiTrans"
	  # icon      = "fa fa-home"
    # Optional logo as brand stored in img/logos
    logo        = "litrans.png"
    projects    = "Projects"
    publication = "Publications"
    team        = "Team"
    news        = "News"
    contact     = "Contact Us"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    # [[menu.postpend]]
    #   url = "http://gohugo.io"
    #   name = "Hugo"
    #   weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title      = "Centre for Urban Innovation @ Ryerson University"
    subtitle   = "Laboratory of Innovations in Transportation"
    buttonText = "Explore"


  # Projects section
  [params.projects]
    enable   = true
    center   = true
    title    = "What We Do"
    subtitle = "Creating Cyber-Physical Future of Urban Mobility using Intelligent Technologies & Mathematics"

    [[params.projects.row]]

      [[params.projects.row.list]]
        icon = "fas fa-car"
        title = "Smart Mobility"
        description = "Distributed traffic management system with application in CAV routing, advanced on-demand transit, traffic management, & system optimization."
        url = "projects/e2ecav2018.pdf"

      [[params.projects.row.list]]
        icon = "fas fa-brain"
        title = "Machine Learning & Mobility"
        description = "Developing data-driven model structure and estimation methods for discrete choice analysis."
        url = "projects/wongfarooq-iatbr-2018.pdf"

      [[params.projects.row.list]]
        icon = "fa fa-user-shield"
        title = "Cybersecurity & Privacy"
        description = "Blockchain framework for Smart Mobility Data-Markets (BSMD) with a focus on cybersecurity and personal privacy."
        url = "https://arxiv.org/pdf/1809.05785.pdf"

      [[params.projects.row.list]]
        icon = "fa fa-vr-cardboard"
        title = "Virtual Reality"
        description = "Virtual Immersive Reality Environment (VIRE) for travel behaviour experiments."
        url = "projects/kalatianfarooq-iatbr-2018.pdf"

      [[params.projects.row.list]]
        icon = "fas fa-city"
        title = "UrbanFlux"
        description = "Ubiquitous sensors network for sensing multimodal traffic in real-time for complete streets"
        url = "https://bilalfarooqdotcom.files.wordpress.com/2018/02/farooq_ryerson_slides.pdf"

  # Publication section
  [params.publication]
    enable = true
	  center = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the
    # 'data' directory at the root of this Hugo site.
    title   = "Recent Publications"
    # subtitle = ""
    display = true

  # News section
  [params.news]
    enable = true
    title  = "News"
    center = false
    # subtitle = ""
    # endpoint = ""

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    links  = false
    title  = "Our Team"
    # subtitle = ""
    # description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.

  # Client section
  [params.clients_list]
    enable = true
    # Possibility to center items
    center = true
    # Optional client title specifying the involvement
    title  = "Affiliations & Funding sources"

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    # Suggestion: .svg in the size of 280px*80px looks good
    [[params.clients]]
      logo = "ryerson.png"
      link = "https://www.ryerson.ca/"

    [[params.clients]]
      logo = "NSERC_RGB.png"
      link = "http://www.nserc-crsng.gc.ca/index_eng.asp"

    [[params.clients]]
      logo = "crc.jpg"
      link = "http://www.chairs-chaires.gc.ca/home-accueil-eng.aspx"

    [[params.clients]]
      logo = "ontario.png"
      link = "https://www.ontario.ca/page/ontario-research-fund"
      
    [[params.clients]]
      logo = "mitacs.png"
      link = "https://www.mitacs.ca/"

    [[params.clients]]
      logo = "cutric.png"
      link = "http://cutric-crituc.org/"

    [[params.clients]]
      logo = "sshrc.jpeg"
      link = "http://www.sshrc-crsh.gc.ca/home-accueil-eng.aspx"

    [[params.clients]]
      logo = "cfi.png"
      link = "https://www.innovation.ca/"

    [[params.clients]]
      logo = "esrc.png"
      link = "https://esrc.ukri.org/"

  # Contact section
  [params.contact]
    enable = true
    title  = "Contact us"
  	mapurl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1443.2139942011902!2d-79.38044537639092!3d43.66006799849111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDPCsDM5JzM2LjIiTiA3OcKwMjInNDcuNSJX!5e0!3m2!1sen!2sca!4v1551126871383&zoom=15"
    addressTitle = "Office"
    address      = "Centre for Urban Innovation<br/>\
	                  CUI-330, Ryerson University<br/>\
				            44 Gerrard Street East, Toronto ON M5G 1G3, Canada"
    phoneNumber  = "416 979-5000 ext 556456"
    # buttonText   = "Send message"

    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "bilal.farooq@ryerson.ca"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    twitter     = "@litrans_lab"
    twitter_url = "https://twitter.com/litrans_lab/"

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    # [params.contact.form.name]
    #   text = "Your Name *"
    #   warning = "Please enter your name."

    # [params.contact.form.email]
    #   text = "Your Email *"
    #   warning = "Please enter your email address."

    # [params.contact.form.phone]
    #   text = "Your Phone *"
    #   warning = "Please enter your phone number."

    # [params.contact.form.message]
    #   text = "Your Message *"
    #   warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      # [[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable    = true
    copyright = "Published under the [Apache License 2.0.](http://www.apache.org/licenses/LICENSE-2.0)"

    # [[params.footer.social]]
    #   icon = "fab fa-twitter"
    #   link = "#"
    #   title = "Twitter"

    # [[params.footer.social]]
    #   icon = "fab fa-facebook"
    #   link = "#"
    #   title = "Facebook"

    # [[params.footer.social]]
    #   icon = "fab fa-github"
    #   link = "#"
    #   title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "/privacy"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "/tos"

    [[params.footer.quicklinks]]
      text = "Hugo"
      link = "http://gohugo.io/"
